apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdal-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gdal-api
  template:
    metadata:
      labels:
        app: gdal-api
    spec:
      containers:
      - name: gdal-api
        image: gdal-rest-api:latest
        ports:
        - containerPort: 8000
